
logging.level.root=INFO
logging.level.com.example.demo=DEBUG
logging.file.name=logs/uygulama-dev.log
logging.pattern.console=%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n


app.message=Development mode active
app.dosya-yolu=/uploads/dev/